/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-alt': '#b71f6c',
        primaryLight: '#e3effb',
        danger: '#f44336',
        safe: '#29b9ff',
        warning: '#f8d200',
        success: '#64A944',
        active: '#f8dc1c',
        'active-font': '#000000',
        container: '#132e52',
        'body-container': '#32a9ff',
        badge: '#ffff00',
        'header-container': '#132e52',
        header: '#132e52',
        'header-container-font': '#f8dc1c',
        'container-header': '#132e52',
        'header-nav': '#194f8f',
        'header-nav-font': '#e0e7ff',
        'event-group': '#132e52',
        'rightbar-container': '#132e52',
        'leftbar-container': '#194f8f',
        'event-title': '#194f8f',
        'odd-item': '#eafffd',
        'odd-item-font': '#000000',
        'mobile-odd-item': '#132e52',
        'odd-item-divider': '#aaabab',
        'mobile-odd-item-font': '#ffffff',
        'event-title-font': '#ffffff',
        'event-item': '#eafffd',
        'event-item-font': '#000000',
        'mobile-event-item': '#194f8f',
        'mobile-event-item-font': '#e0e7ff',
        'event-font': '#ffffff',
        'bet-summery': '#d9f2ff',
        'bet-summery-font': '#0b2810',

        // New variables start
        'header-nav-icon': '#ffffff',
        'sport-types-contianer': '#32a9ff',

        'event-match-header': '#bce8ff',
        'event-match-header-font': '#aaabab',

        'more-odds-btn': '#eafffd',
        'more-odds-btn-font': '#000000',
        'mobile-more-odds-btn': '#132e52',
        'mobile-more-odds-btn-font': '#ffffff',

        'match-detail-contianer': '#374653',
        'match-detail-header': '#59c5ff',
        'match-detail-header-font': '#ffffff',
        'match-detail-events-container': '#59c5ff',
        'match-detail-odds-container': '#bce8ff',

        'leftbar-group-header': '#bce8ff',
        'leftbar-group-header-font': '#000000',
        'leftbar-group-items': '#eafffd',
        'leftbar-group-items-font': '#0b2810',
        'leftbar-group-sport': '#d9f2ff',
        'leftbar-group-sport-font': '#000000',
        'leftbar-country': '#192a52',
        'leftbar-country-font': '#ffffff',
        'leftbar-sport-type': '#2b2e2e',
        'leftbar-sport-type-font': '#ffffff',

        'rightbar-picked-odd-item': '#ffffff',
        'rightbar-picked-odd-item-font': '#000000',
        'rightbar-picked-odd-highligher': '#3b3e3e',

        'bet-stake': '#32a9ff',
        'bet-stake-font': '#000000',

        'table-container': '#2b2e2e',
        'table-header': '#3b3e3e',
        'table-header-font': '#ffffff',
        'table-body': '#eafffd',
        'table-body-font': '#0b2810',
        'mobile-table-body': '#374653',
        'mobile-table-body-font': '#ffffff',

        'secondary-button': '#132e52',
        'secondary-button-font': '#e3effb',
        'secondary-font': '#e3effb',

        'drop-down-menu': '#eafffd',
        'drop-down-menu-font': '#0b2810',
        'slip-icon': '#ffffff',
        'slip-icon-font': '#0b2810',
        'slip-badge': '#ffffff',
        'slip-badge-font': '#32a9ff',
        'slip-badge-active': '#f8dc1c',
        'slip-badge-active-font': '#000000',
        'slip-tab-container': '#204081',
        'slip-container': '#ffffff',

        'nav-border': '#f8dc1c',
        'nav-search-input': '#bce8ff',
        'nav-search-input-font': '#000',
        'nav-search-button': '#132e52',
        'nav-search-button-font': '#e0e7ff',
        'market-search': '#192a52',
        'market-search-font': '#e3effb',
        'ticket-input': '#8edbff',
        'ticket-input-font': '#000000',

        'accumulator-input': '#e0e7ff',
        'accumulator-input-font': '#000000',

        'lobby-games-list': '#1F232D',
        'lobby-games-list-font': '#e0e7ff',
        'match-event-time-font': '#AAABAB',

        'footer-item-font': '#eafffd',
        'footer-item-active-font': '#f8dc1c',

        'jackpot-container': '#000000',
        'jackpot-container-font': '#f8dc1c',

        'jackpot-detail-btn': '#192a52',
        'jackpot-detail-font': '#ffffff',
        'jackpot-detail-timer-btn': '#6B7280',
        'jackpot-detail-container': '#4d5151',
        'jackpot-detail-place-bet-btn': '#f8dc1c',
        'jackpot-detail-reserve-header': '#2b2e2e',
        'jackpot-detail-place-bet-btn-font': '#000000',
        'jackpot-detail-event-odd-item': '#3b3e3e',

        // New variables end
        mute: '#aaabab',
        dark: '#000000',
        secondary: {
          DEFAULT: '#4d5151',
          50: '#2c2e2e',
          100: '#ffffff',
          200: '#ffffff',
          300: '#bce8ff',
          400: '#858b8a',
          500: '#f8dc1c',
          600: '#132e52',
          700: '#374653',
          800: '#eafffd',
          900: '#3ab54a',
          950: '#000000',
        },

        primary: {
          // DEFAULT: '#234caa',
          50: '#eef9ff',
          100: '#d9f2ff',
          200: '#bce8ff',
          300: '#8edbff',
          400: '#59c5ff',
          500: '#32a9ff',
          600: '#175cb6',
          700: '#132e52',
          800: '#175cb6',
          900: '#132e52',
          950: '#132e52',
        },

        'font-primary': '#12548b',
        'font-dark': '#e3effb',
        'font-light': '#0b2810',
      },
      // backgroundImage: {
      //   header: 'linear-gradient(to top, #ffffff, #55c9f6)',
      // },
      screens: {
        xs: '350px',
      },

      minWidth: {
        sm: '20rem',
      },
      maxWidth: {
        lg: '24rem',
      },
    },
  },
  plugins: [],
};
